// "use client"
// import { Metadata } from "next";
// import Image from "next/image";
import Link from "next/link";
// import { CSSProperties } from "react";
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';

type Category = {
  name: string,
  icon: string,
  slug: string
}

import { FaChevronRight } from "react-icons/fa";
import LandingCards from "@/components/landingCards";
// import { useEffect, useState } from "react";
// import LandingSection from "@/components/landing-section/landingSection";
import WhiteBtn from "@/components/btns/whiteBtn";
import Landing from "@/components/sections/landing";
import SwiperTop from "@/components/swipers/swiperTop";
import SwiperBot from "@/components/swipers/swiperBot";

// export const metadata: Metadata = {
//   title: {
//     absolute: "",
//     default: "Baby Shop",
//     template: "Product %s",
//   },
//   description: "Generated by create next app",
// };
async function getData() {
  const res = await fetch('https://competition-e-commerce-backend-1.vercel.app/categories')
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error('Failed to fetch data')
  }

  return res.json()
}
export default async function Home() {
  // const [data, setData] = useState<Category[]>([]);
  let dataPre = await getData()
  let data: Category[] = dataPre.categories
  // useEffect(() => {
  //   fetch("https://competition-e-commerce-backend-1.vercel.app/categories/")
  //     .then(e => e.json()).then(e => setData(e.categories))
  // }, [])
  // const btnStyles: CSSProperties = {
  //   backgroundColor: "gray",
  //   padding: "0 4px",
  //   borderRadius: "4px",
  //   cursor: "pointer"
  // }
  return (
    <main className="flex flex-col items-center p-5 xl:xp-1.5 gap-8">
      <div className="p-5 flex flex-col items-center gap-8 w-full">
        <div className="landing flex flex-col lg:flex-row w-full gap-8 text-gray-800 max-w-[1600px] mx-auto">
          <div className="landing-swiper w-full lg:w-3/5 h-[60vh] rounded-lg overflow-hidden">
            <SwiperTop />
          </div>
          <div className="w-full lg:w-2/5 bg-[#CADEE5] rounded-lg overflow-hidden flex items-center justify-center">
            <div className="flex flex-col items-center p-4 h-full max-h-[380px]">
              <h2 className="text-4xl font-bold">Special offer</h2>
              <p className="text-lg">Baby slippers</p>
              <img width="150" src="https://themes.muffingroup.com/be/babyshop2/wp-content/uploads/2023/11/babyshop2-product-pic8.webp" alt="" />
              <ul className="flex gap-4 text-3xl mb-auto">
                <li className="flex flex-col justify-center items-center">
                  <h3>00</h3>
                  <p className="text-lg">days</p>
                </li>
                <li className="flex flex-col justify-center items-center">
                  <h3>00</h3>
                  <p className="text-lg">hours</p>
                </li>
                <li className="flex flex-col justify-center items-center">
                  <h3>00</h3>
                  <p className="text-lg">minutes</p>
                </li>
                <li className="flex flex-col justify-center items-center">
                  <h3>00</h3>
                  <p className="text-lg">seconds</p>
                </li>
              </ul>
              <WhiteBtn>Buy now</WhiteBtn>
            </div>
          </div>
        </div>
        <div className="landing-categories max-w-[1600px] mx-auto w-full ">
          <LandingCards data={data} />
        </div>
        <Landing />
      </div>
      <section className='flex w-full'>
        <div className="landing-section-swiper w-full h-[65vh] rounded-lg overflow-hidden text-[#2e3331]">
          <SwiperBot />
        </div>
      </section>
      <div className="p-5 flex flex-col items-center gap-8 w-full">
        <Landing />
      </div>
    </main>
  );
}
